In [23]:
import numpy as np
import sys
if "../" not in sys.path:
  sys.path.append("../") 
from lib.envs.gridworld import GridworldEnv

In [24]:
env = GridworldEnv()

In [28]:
def policy_eval(policy, env, discount_factor=1.0, theta=0.00001):
    """
    Evaluate a policy given an environment and a full description of the environment's dynamics.
    
    Args:
        policy: [S, A] shaped matrix representing the policy.
        env: OpenAI env. env.P represents the transition probabilities of the environment.
            env.P[s][a] is a (prob, next_state, reward, done) tuple.
        theta: We stop evaluation once our value function change is less than theta for all states.
        discount_factor: gamma discount factor.
    
    Returns:
        Vector of length env.nS representing the value function.
    """
    # Start with a random (all 0) value function
    V = np.zeros(env.nS)
#     print ("env.nS is:", env.nS) 
#     print(V)
    while True:
        delta = 0
#         对于每个状态，对应于策略中的当前状态的每个action，求它的状态值函数，两种方式都可以：来自PPT和教材。
        for s in range(env.nS):
            v = 0
            for action, action_pi in enumerate(policy[s]):
                for prob, next_state, reward, done in env.P[s][action]:
                    v += action_pi * (reward + discount_factor * prob * V[next_state])
#                     v += action_pi * prob * (reward + discount_factor  * V[next_state])  
#                     implement in solution
            delta = max(delta, np.abs(v - V[s]))
            V[s] = v
        if delta < theta:
            break
    return np.array(V)

In [37]:
random_policy = np.ones([env.nS, env.nA]) / env.nA
v = policy_eval(random_policy, env)
v = np.ceil(v- 0.5)
print(v.reshape(4,4))

env.nS is: 16
[[ -0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.  -0.]]


In [38]:
# Test: Make sure the evaluated policy is what we expected
expected_v = np.array([0, -14, -20, -22, -14, -18, -20, -20, -20, -20, -18, -14, -22, -20, -14, 0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)